### ISSUE TITLE
Comparing Hashes Across Domains

### ISSUE THREAD

**Issue by DoctorQuandary** [MichaelGrafnetter/DSInternals#100]
Get-ADReplAcount + Test-PasswordQuality
This script works very well in a single domain.
As an experiment i tried combining the Get-ADReplAccount results from two domains (This works), and passing them both to Test-PasswordQuality in an attempt to compare hashes across two domains.

This sort of worked, however it had some issues.
It was capable of comparing hashes across domains, but duplicate samaccountnames seemingly got dropped off the list (with no error).

Consider making it possible to collect Get-ADReplAccount data from multiple domains and compare them all in the same Test-PasswordQuality.

**Comment by MichaelGrafnetter** [comment]
Thanks for the feature request. Multi-domain / multi-forest support is definitely on my TODO list for the upcoming months. Unfortunately, it’s implementation requires a couple of changes in the database abstraction layer.

**Comment by aseigler** [comment]
I need this (multi-domain at least) and have the time to implement. Were you looking to switch to UPN or did you have another approach in mind?

**Comment by MichaelGrafnetter** [comment]
Thanks, @aseigler . It is much more complex than that, as UPN is an optional attribute and it is quite often not populated.

My idea was adding a `LogonName` property to the [DSAccount class](https://github.com/MichaelGrafnetter/DSInternals/blob/master/Src/DSInternals.Common/Data/Principals/DSAccount.cs), that would contain `NetBIOSDomainName\SamAccountName`, e. g. `CONTOSO\Administrator`. The `Test-PasswordQuality` cmdlet would then use this property as account identifier instead of `SamAccountName`.  The reason is that instances of the DsAccount class are the only information passed from `Get-ADReplAccount`, `Get-ADDBAccount` and `Get-ADSIAccount` to `Test-PasswordQuality`.

`NetBIOSDomainName` would be a new abstract property of the [DirectoryObject class](https://github.com/MichaelGrafnetter/DSInternals/blob/master/Src/DSInternals.Common/Data/DirectoryObject.cs), which has 3 different implementations:
- In offline DB access, the `NetBIOSDomainName` property is already present on the [DomainController class](https://github.com/MichaelGrafnetter/DSInternals/blob/master/Src/DSInternals.DataStore/DomainController.cs), accessible through the [DirectoryContext singleton](https://github.com/MichaelGrafnetter/DSInternals/blob/master/Src/DSInternals.DataStore/DirectoryContext.cs).
- For MS-DRSR, I would add a `NetBIOSDomainName` property to the [DrsConnection class](https://github.com/MichaelGrafnetter/DSInternals/blob/master/Src/DSInternals.Replication.Interop/DrsConnection.h). Its value needs to be retrieved and cached upon connection through the [IDL_DRSDomainControllerInfo call](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-drsr/668abdc8-1db7-4104-9dea-feab05ff1736), which I have not yet implemented. This is the hardest part, as it involves writing some `C++` and `C` code, with MIDL memory allocators and deallocators.
- Retrieving `NetBIOSDomainName` through ADSI/LDAP access is the easiest one.

Regardless of the account retrieval method, `NetBIOSDomainName` should probably be injected to `DirectoryObject` child classes through their constructors.

What do you think, @aseigler ? I admit that I could have designed the data model in a much better way, but DSInternals originated as a quick-and-dirty PoC.

**Comment by MichaelGrafnetter** [comment]
UPDATE: After digigng into MS-DRSR, I am actually not sure if it can be used to retrieve NetBIOSDomainName, so my approach is probably wrong. But the first object in replication results is NC head, which at least contains Domain DNS name. I hope that there is an easier way of getting NetBIOSDomainName  than replicating the domain partition cross-ref object.

**Comment by aseigler** [comment]
OK, I will investigate.

**Comment by MichaelGrafnetter** [comment]
UPDATE2: Using IDL_DRSCrackNames to translate DC's name/guid to its [DS_NT4_ACCOUNT_NAME](https://docs.microsoft.com/en-us/windows/win32/api/ntdsapi/ne-ntdsapi-ds_name_format) and parsing out NetBIOSDomainName might do the job.

**Comment by DoctorQuandary** [comment]
Great! I'll be following this for any updates.
Distinguished name output would also be useful, as that could be parsed for domain name, username, and OU Location.

**Comment by MichaelGrafnetter** [comment]
The current implementation only stores logins (SamAccountName) of accounts that violate each of the best practices, inside of a [SortedSet<string>](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.sortedset-1?view=netframework-4.8), see the [PasswordQualityTestResult class](https://github.com/MichaelGrafnetter/DSInternals/blob/master/Src/DSInternals.PowerShell/Types/PasswordQualityTestResult.cs). The original [DSAccount data structure](https://github.com/MichaelGrafnetter/DSInternals/blob/master/Src/DSInternals.Common/Data/Principals/DSAccount.cs) is dropped on the fly to save RAM, as I need DSInternals to handle databases with 1M+ user accounts.

An alternative approach would involve creation of lightweight account objects with just a handful of attributes (DN, SamAccountName, UPN) and indexing the items by distinguished name. That would probably solve both feature requests.

**Comment by aseigler** [comment]
> UPDATE2: Using IDL_DRSCrackNames to translate DC's name/guid to its [DS_NT4_ACCOUNT_NAME](https://docs.microsoft.com/en-us/windows/win32/api/ntdsapi/ne-ntdsapi-ds_name_format) and parsing out NetBIOSDomainName might do the job.

So I went after the MS-DRSR path first since it was the hardest and the one I actually need right now.  It was pretty trivial to get the NetBIOSDomainName from IDL_DRSCrackNames (via [DrsConnection::ResolveName()](https://github.com/MichaelGrafnetter/DSInternals/blob/70351197386387a8656dfafa384b63d219b2ed68/Src/DSInternals.Replication.Interop/DrsConnection.cpp#L399)) in the [DrsConnection constructor](https://github.com/MichaelGrafnetter/DSInternals/blob/70351197386387a8656dfafa384b63d219b2ed68/Src/DSInternals.Replication.Interop/DrsConnection.cpp#L24), but the best way I could figure to get an acceptable name to give to IDL_DRSCrackNames in a formatOffered that works is to pass the  DC SPN i.e. ldap/servername.domain.com in the [DirectoryReplicationClient contructor](https://github.com/MichaelGrafnetter/DSInternals/blob/70351197386387a8656dfafa384b63d219b2ed68/Src/DSInternals.Replication/DirectoryReplicationClient.cs#L48), the same as is done when the [RPC connection is authenticated](https://github.com/MichaelGrafnetter/DSInternals/blob/70351197386387a8656dfafa384b63d219b2ed68/Src/DSInternals.Replication/DirectoryReplicationClient.cs#L216).  Is that what you had in mind, or is there some other way to get the connected DC name out of RPC binding?

**Comment by MichaelGrafnetter** [comment]
Great, thanks! Just please test if it works if the server name is "localhost" or IP address. Yes, I meant the NetBIOSDomainName  to be retrieved in constructor, either DrsConnection or DirectoryReplicationClient.
But if this is not possible, let's switch to the alternate approach from my previous comment.

**Comment by aseigler** [comment]
Yeah...neither localhost nor IP address work because the SPN does not match those. IDL_DRSDomainControllerInfo doesn't help either because we don't have the domain name at this point.

**Comment by MichaelGrafnetter** [comment]
Hi @aseigler, I have found a universal way of getting NetBIOSDomainName and DomainNamingContext through MS-DRSR. It involves a sequence of three IDL_DRSCrackNames calls. I first get the list of FSMO roles, then I fetch the ServerReference object of the PDC Emulator and I finally translate its distinguished name to NT4 account name and parse out the domain part. Commit is on its way, but I first need to refactor the code a little.

**Comment by MichaelGrafnetter** [comment]
So domain name retrieval through MS-DRSR is finished, see commit 770a99ad0e4c0bf5c8610a1fbc7504495828fa1e. I only needed to modify 20+ files to achieve it :wink:. I still need to add this info to the DsAccount class.

**Comment by aseigler** [comment]
So I've got this fully implemented as you describe, but I think I've run into a regression in commit 3c6c5e6 with Get-ADSIAccount.  Issue is [here](https://github.com/MichaelGrafnetter/DSInternals/blob/70351197386387a8656dfafa384b63d219b2ed68/Src/DSInternals.Common/ADSI/AdsiObjectAdapter.cs#L100), textValues is null if msDS-KeyCredentialLink value is not present, throws source is required.  I was able to get around the problem quick and easy by changing "textValues" to "textValues?" on the next line, but I wasn't sure if you'd want to solve this problem this way or some other way, and if you would want this fix in the same commit/PR or have them seperated.

**Comment by DoctorQuandary** [comment]
I can't seem to successfully compile the module from the new source code myself.
If either of you could provide me the newly compiled powershell module i'd be willing to test it out and provide feedback.
Thanks.

**Comment by MichaelGrafnetter** [comment]
The build is here: https://dev.azure.com/DSInternals/DSInternals%20CI/_build/results?buildId=169&view=artifacts&type=publishedArtifacts
I am also working on GitHub Actions support, so that GitHub builds the PS module upon every commit.

**Comment by DoctorQuandary** [comment]
It works!
Scenario: Two domains, two pairs of users with the same password.
Result:
These groups of accounts have the same passwords:
  Group 1:
    DomainA\UserA
    DomainB\UserB
  Group 2:
    DomainA\User
    DomainB\User

I appreciate all the work you guys have done!

**Comment by MichaelGrafnetter** [comment]
Published. See [release 4.2](https://github.com/MichaelGrafnetter/DSInternals/releases/tag/v4.2).
