### ISSUE TITLE
Can't read NTHash Attribute

### ISSUE THREAD

**Issue by louissanchez84** [MichaelGrafnetter/DSInternals#62]
I know I'm just doing something stupid here, but how do I read the nthash directly from the object or the nthashhistory? I want to compare history to look for password reuse.

$Object.NTHash, just gives me an array of bytes of data. Same thing with nthashhistory. I see when you look at the object in it's entirely it's nicely formated with Hash01 Hash02 etc

**Comment by MichaelGrafnetter** [comment]
I see. Well, I internally work with hashes and keys in byte arrays, as that's their native representation and all Crypto functions expect this format. For on-screen display/export I use the [ConvertTo-Hex cmdlet](https://github.com/MichaelGrafnetter/DSInternals/blob/master/Documentation/PowerShell/ConvertTo-Hex.md). Or you can pipe `Get-AD*Account` to `Format-Custom -View JohnNTHistory` or `Format-Custom -View HashcatNTHistory` in order to get something very close to what you want.

**Comment by louissanchez84** [comment]
Thank you!

For some reason I couldn't use the Format-Custom, but I was able to use ConvertTo-Hex. I"ll use the the group-object and count member to look for password reuse.
