### ISSUE TITLE
LastLogon empty

### ISSUE THREAD

**Issue by itpro-tips** [MichaelGrafnetter/DSInternals#98]
Hello,
The LastLogon attribute seems not working with _Get-ADReplicationAccount_ 
The value is always empty for all the users.

Environment : Domain controllers 2016 (FFL/DFL 2016)

**Comment by MichaelGrafnetter** [comment]
Good point! The [lastLogon](https://docs.microsoft.com/en-us/windows/win32/adschema/a-lastlogon) attribute is [never replicated](https://docs.microsoft.com/en-us/windows/win32/adschema/a-lastlogon#remarks), so it is empty by design. I might add support for the [lastLogonTimestamp](https://docs.microsoft.com/en-us/windows/win32/adschema/a-lastlogontimestamp), which is replicated between DCs.

**Comment by MichaelGrafnetter** [comment]
I have modified the behavior in commit 9bda022f0c47144497067723f6f90abdb633a83f slightly. Accounts now have 3 properties: `LastLogon`, `LastLogonTimestamp` and `LastLogonDate`. The `LastLogonDate` property will contain `LastLogon`, with fallback to `LastLogonTimestamp` if not set. And it works with Get-ADDBAccount, Get-ADReplAccount, and Get-ADSIAccount. Available since release 4.3.
